# Generated by Django 5.0.6 on 2024-06-24 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='YogaeventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запись на мероприятие',
                'verbose_name_plural': 'Запись на мероприятия',
                'db_table': 'YogaeventRequest',
            },
        ),
        migrations.CreateModel(
            name='Asana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=80, verbose_name='Название асаны')),
                ('translate', models.CharField(blank=True, db_column='Translate', max_length=80, verbose_name='Перевод с санскрита')),
                ('effect', models.TextField(db_column='Effect', max_length=10000, verbose_name='Показания')),
                ('contraindication', models.TextField(db_column='Сontraindication', max_length=10000, verbose_name='Противопоказания')),
                ('technique', models.TextField(db_column='Technique', max_length=10000, verbose_name='Техника выполнения')),
                ('image', models.ImageField(blank=True, db_column='Image', default=None, null=True, upload_to='yoga/images/%Y/%m/%d/', verbose_name='Изображение асаны')),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_column='UploadDate', verbose_name='Дата создания')),
                ('views', models.IntegerField(db_column='Views', default=0, verbose_name='Просмотры')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asanas', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Асана',
                'verbose_name_plural': 'Асаны',
                'db_table': 'Asanas',
            },
        ),
        migrations.CreateModel(
            name='YogaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(db_column='Place', max_length=500, verbose_name='Место проведения')),
                ('time_event', models.TextField(db_column='Time_event', max_length=500, verbose_name='Время проведения')),
                ('description', models.TextField(db_column='Description', max_length=10000, verbose_name='Описание')),
                ('image_event', models.ImageField(blank=True, db_column='Image_event', default=None, null=True, upload_to='yoga/images/%Y/%m/%d/', verbose_name='Изображение мероприятия')),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_column='UploadDate', verbose_name='Дата загрузки')),
                ('status', models.BooleanField(db_column='Status', default=True, verbose_name='Статус')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yogaevents', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'YogaEvent',
            },
        ),
    ]
