# Generated by Django 5.0.6 on 2024-06-25 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asana',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_asanas', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
