# Generated by Django 5.0.6 on 2024-07-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0002_asana_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaevent',
            name='link',
            field=models.TextField(blank=True, db_column='Link', default=None, max_length=250, null=True, verbose_name='Ссылка'),
        ),
    ]
