# Generated by Django 5.0.6 on 2024-07-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0003_yogaevent_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaevent',
            name='link_2',
            field=models.TextField(blank=True, db_column='Link_2', default=None, max_length=250, null=True, verbose_name='Ссылка на место'),
        ),
    ]
