# Generated by Django 5.0.6 on 2024-07-22 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0004_yogaevent_link_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=80, verbose_name='Название статьи')),
                ('description', models.TextField(db_column='Description', max_length=10000, verbose_name='Описание')),
                ('link', models.TextField(blank=True, db_column='Link', default=None, max_length=250, null=True, verbose_name='Ссылка')),
                ('image_text', models.ImageField(blank=True, db_column='Image', default=None, null=True, upload_to='yoga/images/%Y/%m/%d/', verbose_name='Изображение асаны')),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_column='UploadDate', verbose_name='Дата создания')),
                ('status', models.BooleanField(db_column='Status', default=True, verbose_name='Статус')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.subject', verbose_name='Тема статьи')),
            ],
        ),
    ]
