# Generated by Django 5.0.6 on 2024-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0005_subject_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaeventrequest',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
